### ISSUE TITLE
Projects: Define SHACL schema to validate a project

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-admin#23]
The project payload is as follows:
```json
{
  "@context": {
    "nxv": "https://bbp-nexus.epfl.ch/vocabs/nexus/core/terms/v0.1.0/",
    "schema": "http://schema.org/",
    "name": {
      "@id": "schema:name"
    },
    "prefixMappings": {
      "@id": "nxv:prefixMappings"
    },
    "config": {
      "@id": "nxv:config"
    },
    "maxAttachmentSize": {
      "@id": "nxv:maxAttachmentSize"
    },
    "description": {
      "@id": "nxv:description"
    },
    "label": {
      "@id": "schema:label"
    },
    "prefix": {
      "@id": "nxv:prefix"
    },
    "namespace": {
      "@id": "nxv:namespace",
      "@type": "@id"
    }
  },
  "@id": "https://example.nexus.com/api/projects/{name}",
  "@type": "nxv:Project",
  "name": "{name}",
  "description": "{desc}",
  "label": "{label}",
  "prefixMappings": [
    {
      "prefix": "nxv",
      "namespace": "https://bbp-nexus.epfl.ch/vocabs/nexus/core/terms/v0.1.0/"
    },
    {
      "prefix": "persons",
      "namespace": "https://shapes.org/persons"
    }
  ],
  "config": {
    "maxAttachmentSize": 10
  }
}
```

We need a shacl schema for this (open).
This is referenced from [here](https://github.com/BlueBrain/nexus-kg/issues/240)

**Comment by MFSY** [comment]
What is the shape of maxAttachmentSize ? Is it a value with a unit (default to 10 G)?

What is the minimal allowed value ?

**Comment by bogdanromanx** [comment]
I would say the minimum value is `0` indicating attachments are not allowed. We can either use a long to represent the size in _bytes_ or use a _quantitative value_? I'm not sure about this... thoughts?

**Comment by MFSY** [comment]
Okay for the minimum. But wouldn't it be better to disabled attachments by setting (or not) a specific permission ?

For simplicity we can pick a single unit (bytes) and ask users to provide a value in that unit (and document that a provided value will be considered as bytes). A long is okay.

**Comment by bogdanromanx** [comment]
Agreed on all points! ;)

**Comment by MFSY** [comment]
Cool

**Comment by MFSY** [comment]
The project schema will need to extend the resource schema [/schemas/nexus/core/resource/v0.1.0](https://github.com/BlueBrain/nexus-commons/blob/master/modules/schemas/src/main/resources/schemas/nexus/core/resource/v0.1.0.json) (because of rev, deprecated, ...) which should then be located in nexus-admin. Thoughts ?

**Comment by MFSY** [comment]
Also what is (will be) the default value for maxAttachmentSize ?

**Comment by bogdanromanx** [comment]
I would say it should be unbounded (`Long.MaxValue`) because it's really a deployment configuration that we need to check at runtime...

Regarding the location of the schemas, I would say we need to keep a core set of schemas in nexus-commons or nexus-service and the service specific ones (like Project) should reside in each of the service. @umbreak, thoughts?

**Comment by umbreak** [comment]
I would say the `schemas` and `contexts` for projects should be self contained, otherwise we need to import context resolution and right now that's not gonna work.
